global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 192.168.100.10:9100
          - 192.168.100.11:9100
          - 192.168.100.12:9100
          - 192.168.100.13:9100

  - job_name: 'promtail'
    static_configs:
      - targets:
          - 192.168.100.10:9080
          - 192.168.100.11:9080
          - 192.168.100.12:9080
          - 192.168.100.13:9080