- name: Download promtail binary
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v2.9.2/promtail-linux-amd64.zip"
    dest: /tmp/promtail.zip
    mode: '0644'

- name: Unzip promtail
  unarchive:
    src: /tmp/promtail.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Ensure promtail is executable
  file:
    path: /usr/local/bin/promtail-linux-amd64
    mode: '0755'

- name: Copy promtail config
  template:
    src: promtail-config.yaml.j2
    dest: /etc/promtail-config.yaml

- name: Create promtail systemd service
  copy:
    dest: /etc/systemd/system/promtail.service
    content: |
      [Unit]
      Description=Promtail service
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/promtail-linux-amd64 -config.file=/etc/promtail-config.yaml
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start promtail
  systemd:
    name: promtail
    enabled: yes
    state: started
    daemon_reload: yes 