- name: Copy docker-compose.yml for monitoring
  copy:
    src: files/docker-compose-monitoring.yml
    dest: /opt/app/docker-compose.yml

- name: Copy monitoring configs
  synchronize:
    src: ../../monitoring/
    dest: /opt/app/monitoring/
    recursive: yes

- name: Start monitoring stack
  shell: docker-compose up -d
  args:
    chdir: /opt/app 